### ISSUE TITLE
Justification regression with groff 1.23.0 (?)

### ISSUE THREAD

**Issue by guillemj** [rra/podlators#23] opened 2023-10-24 20:45 UTC
Hi!

I recently noticed that in Debian unstable, manual pages generated from pod, are no longer left aligned everywhere. They are at the beginning, but for example once there are options the justification gets set to both. I think this is a regression in combination with groff 1.23.0, but I've not tested the current stuff from Debian unstable with an older groff (only verifyied that bookworm behaves as expected), nor know whether this is a problem in groff (some kind of regression) or in podlators (some misuse or wrong assumption for some macro perhaps).

Just wanted to file this to not forget.

**Comment by rra** [comment] 2023-10-24 20:54
Yeah, I noticed this too and it does seem to be related to `.IP`/`.TP`. I also suspect that this is a groff regression. I need to join the groff mailing list and inquire.

**Comment by rra** [comment] 2024-03-15 05:09
This is because of the addition of:
```
.  ad \\*[AD]
```
to the `an-write-paragraph-tag` function in the `an` macro set, so far as I can tell. I have inquired on the groff mailing list if there's some way that I can support the intent of the AD register but still change the default under nroff to ragged right justification instead of full justification.

BTW, I believe the intent of this AD macro is that you can set `MANROFFOPT` to `-dAD=l` and get ragged right justification for every man page, not just the ones generated by pod2man.

**Comment by guillemj** [comment] 2024-03-15 23:36
Ah, thanks for the investigation! I've now set MANROFFOPT in my environment to get a uniform style, although it would indeed be best if what pod2man generates could be formatted as before. :)

**Comment by rra** [comment] 2024-03-17 19:57
Branden agreed that this is a regression and a fix has been committed to the groff repository for the next release. We're currently discussing what, if anything, Pod::Man should do in the meantime, which depends on release schedules, etc. I'd also kind of like to support the `AD` register properly if someone really wants full justification.

I'm trying to talk Branden into making the default ragged right under nroff for all man pages. That's a big change since groff has always defaulted to full justification, but older UNIX nroff did default to ragged right.

Discussion is in the thread starting at https://lists.gnu.org/archive/html/groff/2024-03/msg00078.html

**Closed** 2024-03-19 03:48 UTC
